//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFOMS_testv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTLPU
    {
        public int HISTLPU_id { get; set; }
        public int p_id { get; set; }
        public string lpu { get; set; }
        public Nullable<System.DateTime> lpudt { get; set; }
        public Nullable<System.DateTime> lpudx { get; set; }
        public string district { get; set; }
        public string subdir { get; set; }
    
        public virtual PEOPLE PEOPLE { get; set; }
    }
}
