//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFOMS_testv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPU
    {
        public int LPU_id { get; set; }
        public string code { get; set; }
        public string caption { get; set; }
        public string bossname { get; set; }
    }
}
