//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFOMS_testv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEOPLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEOPLE()
        {
            this.HISTLPU = new HashSet<HISTLPU>();
        }
    
        public int p_id { get; set; }
        public string enp { get; set; }
        public string fam { get; set; }
        public string im { get; set; }
        public string ot { get; set; }
        public int w { get; set; }
        public System.DateTime dr { get; set; }
        public string lpu { get; set; }
        public Nullable<System.DateTime> lpudt { get; set; }
        public Nullable<System.DateTime> lpudx { get; set; }
        public string lpuuch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTLPU> HISTLPU { get; set; }
    }
}
