//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFOMS_testv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T001
    {
        public int T001_id { get; set; }
        public string mcod { get; set; }
        public string nam_me { get; set; }
        public string nom_podr { get; set; }
    }
}
