//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFOMS_testv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T007
    {
        public int T007_id { get; set; }
        public string code_mo { get; set; }
        public string name_depth { get; set; }
        public string nom_podr { get; set; }
        public string depth { get; set; }
    }
}
